import {
  Company,
  DevTool,
  type Position,
  PositionRole,
  PositionType,
} from "../types/work.ts";

export const Positions: Position[] = [
  {
    id: 1,
    company: Company.Yanport,
    role: PositionRole.Backend,
    isLeadRole: false,
    type: PositionType.Internship,
    mainDevTool: DevTool.Java,
    feDevTools: [],
    beDevTools: [DevTool.Java, DevTool.Jsoup],
    period: [new Date(2016, 0), new Date(2016, 2)],
  },
  {
    id: 2,
    company: Company.Yanport,
    role: PositionRole.FullStack,
    isLeadRole: false,
    type: PositionType.WorkStudy,
    mainDevTool: DevTool.AngularJS,
    feDevTools: [DevTool.AngularJS, DevTool.Bootstrap, DevTool.Javascript],
    beDevTools: [
      DevTool.Cassandra,
      DevTool.Datastore,
      DevTool.Elasticsearch,
      DevTool.Java,
      DevTool.Jsoup,
      DevTool.RabbitMq,
    ],
    period: [new Date(2016, 6), new Date(2017, 10)],
  },
  {
    id: 3,
    company: Company.Yanport,
    role: PositionRole.FullStack,
    isLeadRole: false,
    type: PositionType.FullTime,
    mainDevTool: DevTool.Angular,
    feDevTools: [
      DevTool.Angular,
      DevTool.AngularJS,
      DevTool.AngularMaterial,
      DevTool.CSSFlexbox,
      DevTool.Javascript,
      DevTool.PWA,
      DevTool.Redux,
      DevTool.Responsive,
      DevTool.SCSS,
      DevTool.SSR,
      DevTool.Typescript,
    ],
    beDevTools: [
      DevTool.Cassandra,
      DevTool.Datastore,
      DevTool.Elasticsearch,
      DevTool.Java,
      DevTool.Jsoup,
      DevTool.RabbitMq,
    ],
    period: [new Date(2017, 10), new Date(2019, 6)],
  },
  {
    id: 4,
    company: Company.RenaultDigital,
    consultingFirm: Company.Onepoint,
    role: PositionRole.Frontend,
    isLeadRole: true,
    type: PositionType.FullTime,
    mainDevTool: DevTool.Angular,
    feDevTools: [
      DevTool.Angular,
      DevTool.AngularMaterial,
      DevTool.CSSFlexbox,
      DevTool.Redux,
      DevTool.SCSS,
      DevTool.Typescript,
    ],
    beDevTools: [],
    period: [new Date(2019, 8), new Date(2022, 0)],
  },
  {
    id: 5,
    company: Company.Chainify,
    role: PositionRole.FullStack,
    isLeadRole: false,
    type: PositionType.PartTime,
    mainDevTool: DevTool.Blockchain,
    feDevTools: [
      DevTool.CSSFlexbox,
      DevTool.CSSGrid,
      DevTool.DaisyUI,
      DevTool.NextJS,
      DevTool.React,
      DevTool.Responsive,
      DevTool.SCSS,
      DevTool.Storybook,
      DevTool.Typescript,
    ],
    beDevTools: [
      DevTool.AzureFunctions,
      DevTool.Blockchain,
      DevTool.CSharp,
      DevTool.Serverless,
      DevTool.Web3,
    ],
    period: [new Date(2022, 4), new Date(2023, 6)],
  },
  {
    id: 6,
    company: Company.Bell,
    consultingFirm: Company.Talan,
    role: PositionRole.Frontend,
    isLeadRole: true,
    type: PositionType.FullTime,
    mainDevTool: DevTool.Vue3,
    feDevTools: [
      DevTool.CSSFlexbox,
      DevTool.CSSGrid,
      DevTool.Element,
      DevTool.ElementPlus,
      DevTool.Responsive,
      DevTool.SCSS,
      DevTool.Storybook,
      DevTool.TailwindCSS,
      DevTool.Typescript,
      DevTool.Vue2,
      DevTool.Vue3,
    ],
    beDevTools: [],
    period: [new Date(2022, 1)],
  },
];
