name: Web3 Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node using mise
        uses: jdx/mise-action@v2

      - name: Install Node dependencies
        shell: bash
        run: pnpm i

      - name: Build for Web3
        run: |
          pnpm build:web3
          rm ./dist/CNAME

      - name: Upload artifact
        id: artifactUpload
        uses: actions/upload-artifact@v4
        with:
          name: "web3-build"
          path: ./dist/
